[project]
name = "mdformat-include"
version = "0.1.0"
description = "An mdformat plugin to include files and keep them synced"
readme = "README.md"
authors = [
    { name = "Kristof Bruyninckx", email = "kristof.bruyninckx1@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "mdformat~=1.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "commitizen>=4.12.1",
    "mypy~=1.19.1",
    "pytest~=9.0.2",
    "ruff~=0.14.14",
]
